#동작 테스트는 Local에서 하고 실제 테스트는 물리적으로 떨어져있어야하기 때문에, 다른 머신에서 테스트한다.

spring:
  datasource:
    shard1:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/shard1_db
      username: shard1_user
      password: shard1_user_password

    shard2:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3307/shard2_db
      username: shard2_user
      password: shard2_user_password

  data:
    mongodb:
#      uri: mongodb://localhost:20000/lab

  sharding:
    tables:
      - table-name: message
        sharding-key: room_id
        sharding-algorithm: range

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.batch_size: 1000 # 배치 크기 설정
        order_inserts: true  # INSERT 정렬
        order_updates: true  # UPDATE 정렬
        batch_versioned_data: true